// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP47TTjOaGoCctc1Wfbz_R3iUzKVL44n0',
    appId: '1:777426261281:web:05cebda1d4cd532bddda60',
    messagingSenderId: '777426261281',
    projectId: 'chatapp-6ebca',
    authDomain: 'chatapp-6ebca.firebaseapp.com',
    storageBucket: 'chatapp-6ebca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfc1Lr23Z7ZHVjCaL8MUVa8a1WfmfzqWs',
    appId: '1:777426261281:android:d9f6f2014f5972baddda60',
    messagingSenderId: '777426261281',
    projectId: 'chatapp-6ebca',
    storageBucket: 'chatapp-6ebca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukCymR6JpVqVdombaJPW82nBDftgiBz8',
    appId: '1:777426261281:ios:9eac14a422ed73e8ddda60',
    messagingSenderId: '777426261281',
    projectId: 'chatapp-6ebca',
    storageBucket: 'chatapp-6ebca.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBukCymR6JpVqVdombaJPW82nBDftgiBz8',
    appId: '1:777426261281:ios:2a12bd99c1f3a684ddda60',
    messagingSenderId: '777426261281',
    projectId: 'chatapp-6ebca',
    storageBucket: 'chatapp-6ebca.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
